// This file is automatically generated -- do not try to change it.
// The NGSPREPROC license applies.

#include "boost/tuple/tuple.hpp"
#include <string> 
#include <map> 
// ngs version tuple: major, minor, bug fix 
typedef boost::tuple<int, int, int> version;
#ifdef __GNUC__ 
  typedef boost::tuple<int, int, int> gcc_version;
#endif

namespace ngs {
     const version VERSION(0,1,0);
     const std::string DATE(" 22. May 2016");
     #ifdef __GNUC__ 
      const gcc_version GCC_VERSION(__GNUC__,__GNUC_MINOR__,__GNUC_PATCHLEVEL__);
     #endif 
} // end namespace ngs
